name: uqrm
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3
  - python=3.9.18
  - pip:
      - accelerate==0.23.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - click==8.1.7
      - datasets==2.14.5
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - evaluate==0.4.1
      - filelock==3.12.4
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - huggingface-hub==0.17.3
      - idna==3.4
      - jinja2==3.1.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - networkx==3.2
      - numpy==1.26.1
      - pandas==2.1.1
      - pathtools==0.1.2
      - pillow==10.1.0
      - protobuf==4.24.4
      - pyarrow==13.0.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.31.0
      - responses==0.18.0
      - rich==13.6.0
      - safetensors==0.4.0
      - sentry-sdk==1.32.0
      - setproctitle==1.3.3
      - shtab==1.6.4
      - smmap==5.0.1
      - sympy==1.12
      - tokenizers==0.14.1
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - tqdm==4.66.1
      - transformers==4.34.1
      - triton==2.1.0
      - trl==0.7.2
      - tyro==0.5.10
      - tzdata==2023.3
      - urllib3==2.0.7
      - wandb==0.15.12
      - xxhash==3.4.1
      - peft==0.5.0
      - bitsandbytes==0.41.1
      - scipy==1.11.3
      - yarl==1.9.2
