name: uqrm
channels:
  - conda-forge
  - defaults
  - pytorch
  - conda
dependencies:
  - pip=23.3
  - python=3.9.18
  - pytorch==2.0.0
  - torchvision==0.15.0
  - torchaudio==2.0.0
  - pytorch-cuda=11.4
  - pip:
      - accelerate==0.23.0
      - datasets==2.14.5
      - evaluate==0.4.1
      - huggingface-hub==0.17.3
      - numpy==1.26.1
      - pandas==2.1.1
      - tokenizers==0.14.1
      - tqdm==4.66.1
      - transformers==4.34.1
      - trl==0.7.2
      - wandb==0.15.12
