name: uqrm
channels:
  - conda-forge
  - defaults
  - pytorch
  - conda
dependencies:
  - python=3.9
  - pip=23.3
  - pip:  
    - torch==2.0.1
    - torchvision==0.15.2
    - torchaudio==2.0.2
    - accelerate==0.26.1
    - datasets==2.16.1
    - evaluate==0.4.1
    - huggingface-hub==0.20.3
    - tokenizers==0.15.2
    - tqdm==4.66.1
    - transformers==4.39.3
    - peft==0.5.0
    - bitsandbytes==0.41.1
    - scipy==1.11.3
    - scikit-learn==1.3.2
    - trl==0.8.1
    - wandb==0.15.12
    - jupyter
    - sentencepiece==0.1.99
    - ai2-olmo==0.2.5
