name: uqrm
channels:
  - conda-forge
  - defaults
  - pytorch
  - conda
dependencies:
  - python=3.9
  - pip=23.3
  - pip:  
    - torch==2.0.1
    - torchvision==0.15.2
    - torchaudio==2.0.2
    - accelerate==0.23.0
    - datasets==2.14.5
    - evaluate==0.4.1
    - huggingface-hub==0.17.3
    - tokenizers==0.14.1
    - tqdm==4.66.1
    - transformers==4.34.1
    - peft==0.5.0
    - bitsandbytes==0.41.1
    - scipy==1.11.3
    - trl==0.7.2
    - wandb==0.15.12
