name: uqrm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - ca-certificates=2023.7.22
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - ipykernel=6.25.2
  - ipython=8.16.1
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.4.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.0.11
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3
  - platformdirs=3.11.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.11.2
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - wcwidth=0.2.8
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - accelerate==0.23.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - click==8.1.7
      - datasets==2.14.5
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - evaluate==0.4.1
      - filelock==3.12.4
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - huggingface-hub==0.17.3
      - idna==3.4
      - jinja2==3.1.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - networkx==3.2
      - numpy==1.26.1
      - pandas==2.1.1
      - pathtools==0.1.2
      - pillow==10.1.0
      - protobuf==4.24.4
      - pyarrow==13.0.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.31.0
      - responses==0.18.0
      - rich==13.6.0
      - safetensors==0.4.0
      - sentry-sdk==1.32.0
      - setproctitle==1.3.3
      - shtab==1.6.4
      - smmap==5.0.1
      - sympy==1.12
      - tokenizers==0.14.1
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - tqdm==4.66.1
      - transformers==4.34.1
      - triton==2.1.0
      - trl==0.7.2
      - tyro==0.5.10
      - tzdata==2023.3
      - urllib3==2.0.7
      - wandb==0.15.12
      - xxhash==3.4.1
      - yarl==1.9.2
